sesion_04/music/urls.py
"""Music app url config"""

from django.urls import path

from . import views


app_name = "music"
urlpatterns = [
    path("songs/", views.show_songs, name="show_songs"),
    path("create-artist/", views.create_artist, name="create_artist"),
    path("create-song/", views.create_song, name="create_song"),
    path("songs/<int:pk>", views.song_detail, name="song_detail"),
    path("artists/", views.show_artists, name="show_artists"),
    path("albums/", views.show_albums, name="show_albums"),
]

sesion_04/napster/urls.py
"""Global Napster URL Configuration"""

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
    path("music/", include("music.urls")),
    path("", include("users.urls")),
]

sesion_04/todos/urls.py
"""TODOs app URL config"""

from django.urls import path

from .views import index

app_name = "todos"
urlpatterns = [
    path("", index, name="index"),
]

sesion_04/users/urls.py
"""Users app URL configuration"""

from django.urls import path

from . import views


app_name = "users"
urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
    path("logout", views.LogoutView.as_view(), name="logout"),
    path("signup", views.SignupView.as_view(), name="signup"),
]

sesion_04/music/models.py
"""Music apps models"""

from django.db import models


class Artist(models.Model):
    """Artist model"""
    name = models.CharField(max_length=255)
    birthday = models.DateField(blank=True, null=True)

    class Meta:
        ordering = ['name', ]

    def __str__(self):
        return self.name


class Album(models.Model):
    """Album model"""
    name = models.CharField(max_length=255)
    release_date = models.DateField(blank=True, null=True)

    class Meta:
        ordering = ['name', ]

    def __str__(self):
        return self.name


class Song(models.Model):
    """Song model"""
    title = models.CharField(max_length=255)
    artist = models.ForeignKey("Artist", on_delete=models.CASCADE)
    album = models.ForeignKey("Album", on_delete=models.CASCADE)

    class Meta:
        ordering = ['title', ]

    def __str__(self):
        return self.title

sesion_04/users/forms.py
"""User app forms"""

from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()


class SignupForm(forms.Form):
    username = forms.CharField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField()
    password_confirmation = forms.CharField()

    def clean_username(self):
        username = self.cleaned_data.get("username")
        username_exists = User.objects.filter(username=username).exists()
        if username_exists:
            raise forms.ValidationError(
                "El nombre de usuario no está disponible"
            )
        return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        email_exists = User.objects.filter(email=email).exists()
        if email_exists:
            raise forms.ValidationError(
                "El correo electrónico ya está en uso"
            )
        return email

    def clean(self):
        data = self.cleaned_data
        password = data.get("password")
        password_confirmation = data.get("password_confirmation")

        if password != password_confirmation:
            raise forms.ValidationError("Las contraseñas no coinciden")

        return data

    def save(self):
        data = self.cleaned_data
        data.pop("password_confirmation")
        return User.objects.create_user(**data)

sesion_04/music/views.py
"""Music app views"""

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .models import Song, Artist, Album


@login_required
def show_songs(request):
    """Muestra las canciones"""
    songs = Song.objects.all()
    return render(request, "music/show-songs.html", {"songs": songs})


@login_required
def song_detail(request, pk):
    """Muestra una canción en específico"""
    song = Song.objects.get(pk=pk)
    return render(request, "music/song-detail.html", {"song": song})


@login_required
def create_artist(request):
    """Crea un artista"""
    if request.method == "POST":
        name = request.POST["name"]
        birthday = request.POST.get("birthday")
        artist = Artist(name=name, birthday=birthday)
        artist.save()
        return redirect("music:show_songs")
    else:
        return render(request, "music/create-artist.html",)


@login_required
def create_song(request):
    """Crea un artista"""
    if request.method == "POST":
        title = request.POST["title"]
        artist_id = request.POST["artist_id"]
        album_id = request.POST["album_id"]
        song = Song(title=title, artist_id=artist_id, album_id=album_id)
        song.save()
        return redirect("music:show_songs")
    else:
        artists = Artist.objects.all()
        albums = Album.objects.all()
        return render(request, "music/create-song.html", {"artists": artists, "albums": albums})


@login_required
def show_artists(request):
    """Muestra los artistas"""
    artists = Artist.objects.all()
    return render(request, "music/show-artists.html", {"artists": artists})


@login_required
def show_albums(request):
    """Muestra los álbumes"""
    albums = Album.objects.all()
    return render(request, "music/show-albums.html", {"albums": albums})

sesion_04/todos/views.py
from django.shortcuts import render

todos = []


def index(request):
    if request.method == "POST":
        new_todo = request.POST['new_todo']
        todos.append(new_todo)
    return render(request, "todos/index.html", {"todos": todos})

sesion_04/users/views.py
"""Users app views"""

from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic as generic_views

from .forms import SignupForm


User = get_user_model()


def login_view(request):
    if request.user.is_authenticated:
        return redirect("music:show_songs")

    context = {}

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if not user:
            context["error"] = "Credenciales inválidas"
        else:
            login(request, user)
            next_url = request.GET.get("next")
            return redirect(next_url if next_url else "music:show_songs")

    return render(request, "users/login.html", context)


def logout_view(request):
    logout(request)
    return redirect("users:login")


def signup(request):
    if request.user.is_authenticated:
        return redirect("music:show_songs")

    form = SignupForm()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("music:show_songs")
    return render(request, "users/signup.html", {"form": form})


class LoginView(auth_views.LoginView):
    template_name = "users/login.html"
    redirect_authenticated_user = True


class LogoutView(auth_views.LogoutView):
    pass


class SignupView(generic_views.FormView):
    template_name = "users/signup.html"
    form_class = SignupForm
    success_url = reverse_lazy("music:show_songs")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(self.success_url)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)

sesion_04/templates/_navbar.html
{% if request.user.is_authenticated %}
  <nav class="navbar is-black">
    <div class="navbar-brand">
      <a class="navbar-item" href="{% url 'music:show_songs' %}">
        Napster
      </a>
    </div>


      <div class="navbar-end">
        <div class="navbar-item">
          <p>@{{ request.user.username }}</p>
        </div>
        <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <a class="button is-danger" href="{% url 'users:logout' %}">
                <span>Cerrar sesión</span>
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </nav>
{% endif %}

sesion_04/templates/base.html
<!doctype html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  {% block css %}
  {% endblock css %}

  {% block title %}
  <title>Napster</title>
  {% endblock title %}
</head>
<body>
  {% include '_navbar.html' %}

  {% block content %}
  {% endblock content %}

  {% block javascript %}
  {% endblock javascript %}
</body>
</html>

sesion_04/templates/music/create-artist.html
{% extends 'base.html' %}

{% block title %}
  <title>Crear artista</title>
{% endblock title %}


{% block content %}
  <section class="section">
    <div class="container">
      <h1 class="title">Crear artista</h1>
      
      <form method="post">
        {% csrf_token %}
        <div class="field">
          <label class="label">Nombre:</label>
          <div class="control">
            <input class="input" type="text" placeholder="Placebo" name="name" />
          </div>
        </div>

        <div class="field">
          <label class="label">Cumpleaños</label>
          <div class="control">
            <input class="input" type="date" placeholder="21-12-1998" name="birthday" />
          </div>
        </div>

        <div class="field is-grouped mt-3">
          <div class="control">
            <button type="submit" class="button is-link">Crear</button>
          </div>
          <div class="control">
            <button type="reset" class="button is-link is-light">Reiniciar</button>
          </div>
        </div>

      </form>      
    </div>
  </section>
{% endblock content %}

sesion_04/templates/music/create-song.html
{% extends 'base.html' %}

{% block title %}
  <title>Crear canción</title>
{% endblock title %}


{% block content %}
  <section class="section">
    <div class="container">
      <h1 class="title">Crear canción</h1>
      
      <form method="post">
        {% csrf_token %}
        <div class="field">
          <label class="label">Título:</label>
          <div class="control">
            <input class="input" type="text" placeholder="Hotel California..." name="title" />
          </div>
        </div>

        <div class="field">
          <label for="artist-id" class="label">Artista:</label>
          <div class="control">
            <div class="select">
              <select name="artist_id" id="artist-id">
                <option>-----------</option>
                {% for artist in artists %}
                <option value="{{ artist.id }}">{{ artist.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
        </div>

        <div class="field">
          <label for="album-id" class="label">Album:</label>
          <div class="control">
            <div class="select">
              <select name="album_id" id="album-id">
                <option>-----------</option>
                {% for album in albums %}
                <option value="{{ album.id }}">{{ album.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
        </div>


        <div class="field is-grouped mt-3">
          <div class="control">
            <button type="submit" class="button is-link">Crear</button>
          </div>
          <div class="control">
            <button type="reset" class="button is-link is-light">Reiniciar</button>
          </div>
        </div>

      </form>      
    </div>
  </section>
{% endblock content %}

sesion_04/templates/music/show-albums.html
{% extends 'base.html' %}

{% block title %}
  <title>Álbumes</title>
{% endblock title %}


{% block content %}
  <section class="section">
    <div class="container">
      <h1 class="title">Álbumes</h1>
      <div class="content">
        <ul>
          {% for album in albums %}
          <li>{{ album.name }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </section>
{% endblock content %}

sesion_04/templates/music/show-artists.html
{% extends 'base.html' %}

{% block title %}
  <title>Artistas</title>
{% endblock title %}


{% block content %}
  <section class="section">
    <div class="container">
      <h1 class="title">Artistas</h1>
      <div class="content">
        <ul>
          {% for artist in artists %}
          <li>{{ artist.name }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </section>
{% endblock content %}

sesion_04/templates/music/show-songs.html
{% extends 'base.html' %}

{% block title %}
  <title>Música</title>
{% endblock title %}


{% block content %}
  <section class="section">
    <div class="container">
      <h1 class="title">Canciones</h1>
      <div class="content">
        <ul>
          {% for song in songs %}
          <li>
            <a href="{% url 'music:song_detail' song.pk %}">{{ song.title }}</a>
            de {{ song.artist.name }}
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </section>
{% endblock content %}

sesion_04/templates/music/song-detail.html
{% extends 'base.html' %}

{% block title %}
  <title>Canción</title>
{% endblock title %}

{% block content %}
  <section class="section">
    <div class="container">
      <h1 class="title">Canción</h1>
      <div class="content">
        <ul>
          <li>Título: {{ song.title }}</li>
          <li>Artista: {{ song.artist.name }}</li>
          <li>Álbum: {{ song.album.name }}</li>
        </ul>
      </div>
    </div>
  </section>
{% endblock content %}

sesion_04/templates/todos/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock css %}

{% block title %}
<title>TODOS</title>
{% endblock title %}

{% block content %}
<section class="hero is-black">
    <div class="hero-body">
      <h1 class="title">
        TODOs
      </h1>
      <p class="subtitle">
        No vuelvas a olvidar hacer algo
      </p>
    </div>
</section>

<section class="section">
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="field">
                <label class="label">Contenido:</label>
                <div class="control">
                  <input class="input" type="text" placeholder="Lavar los platos..." name="new_todo" />
                </div>
            </div>
            <button  class="button is-link" type="submit">Crear</button>
        </form>
        
        <div class="content">
            <ul>
                {% for todo in todos %}
                    <li>{{ todo }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</section>
{% endblock content %}

{% block javascript %}
<script src="{% static 'js/index.js' %}"></script>
{% endblock javascript %}

sesion_04/templates/users/login.html
{% extends 'base.html' %}

{% block title %}
  <title>Iniciar sesión</title>
{% endblock title %}


{% block content %}
  <section class="section">
    <div class="container">
      {% if form.errors %}
      <div class="notification is-danger is-light">
        Credenciales inválidas, inténtalo de nuevo
      </div>
      {% endif %}

      <h1 class="title">Iniciar sesión</h1>
      
      <form method="post">
        {% csrf_token %}
        <div class="field">
          <label class="label">Nombre de usuario:</label>
          <div class="control">
            <input class="input" type="text" name="username" />
          </div>
        </div>

        <div class="field">
          <label class="label">Contraseña:</label>
          <div class="control">
            <input class="input" type="password" name="password" />
          </div>
        </div>

        <div class="field is-grouped mt-5">
          <div class="control">
            <button type="submit" class="button is-link">Iniciar sesión</button>
          </div>
          <div class="control">
            <button type="reset" class="button is-link is-light">Reiniciar</button>
          </div>
        </div>

        <input type="hidden" name="next" value="{{ next }}">
      </form>      
    </div>
  </section>
{% endblock content %}

sesion_04/templates/users/signup.html
{% extends 'base.html' %}

{% block title %}
  <title>Crear usuario</title>
{% endblock title %}


{% block content %}
  <section class="section">
    <div class="container">
      {% for error in form.non_field_errors %}
      <div class="notification is-danger is-light">
        {{ error }}
      </div>
      {% endfor %}

      <h1 class="title">Crear usuario</h1>
      
      <form method="post">
        {% csrf_token %}
        <div class="field">
          <label for="username-id" class="label">Nombre de usuario:</label>
          <div class="control">
            <input
              class="input{% if form.username.errors %} is-danger{% endif %}"
              type="text"
              name="username"
              id="username-id"
              {% if form.errors %}value="{{ form.username.value }}"{% endif %}
              required
              />
          </div>
          {% for error in form.username.errors %}
          <p class="help is-danger">{{ error }}</p>
          {% endfor %}
        </div>

        <div class="field">
          <label for="first-name-id" class="label">Nombre(s):</label>
          <div class="control">
            <input
              class="input{% if form.first_name.errors %} is-danger{% endif %}"
              type="text"
              name="first_name"
              id="first-name-id"
              {% if form.errors %}value="{{ form.first_name.value }}"{% endif %}
              required
            />
          </div>
          {% for error in form.first_name.errors %}
          <p class="help is-danger">{{ error }}</p>
          {% endfor %}
        </div>

        <div class="field">
          <label for="last-name-id" class="label">Apellido(s):</label>
          <div class="control">
            <input
              class="input{% if form.last_name.errors %} is-danger{% endif %}"
              type="text"
              name="last_name"
              id="last-name-id"
              {% if form.errors %}value="{{ form.last_name.value }}"{% endif %}
              required
            />
          </div>
          {% for error in form.last_name.errors %}
          <p class="help is-danger">{{ error }}</p>
          {% endfor %}
        </div>

        <div class="field">
          <label for="email-id" class="label">Correo electrónico:</label>
          <div class="control">
            <input
              class="input{% if form.email.errors %} is-danger{% endif %}"
              type="email"
              name="email"
              id="email-id"
              {% if form.errors %}value="{{ form.email.value }}"{% endif %}
              required
            />
          </div>
          {% for error in form.email.errors %}
          <p class="help is-danger">{{ error }}</p>
          {% endfor %}
        </div>

        <div class="field">
          <label for="password-id" class="label">Contraseña:</label>
          <div class="control">
            <input
              class="input{% if form.password.errors %} is-danger{% endif %}" 
              type="password"
              name="password"
              id="password-id"
              required
            />
          </div>
          {% for error in form.password.errors %}
          <p class="help is-danger">{{ error }}</p>
          {% endfor %}
        </div>

        <div class="field">
          <label for="password-confirmation-id" class="label">Confirmar contraseña:</label>
          <div class="control">
            <input
              class="input{% if form.password_confirmation.errors %} is-danger{% endif %}"
              type="password"
              name="password_confirmation"
              id="password-confirmation-id"
              required
            />
          </div>
          {% for error in form.password_confirmation.errors %}
          <p class="help is-danger">{{ error }}</p>
          {% endfor %}
        </div>

        <div class="field is-grouped mt-5">
          <div class="control">
            <button type="submit" class="button is-link">Enviar</button>
          </div>
          <div class="control">
            <button type="reset" class="button is-link is-light">Reiniciar</button>
          </div>
        </div>

      </form>      
    </div>
  </section>
{% endblock content %}